# Linear Regression with pytorch using torch.nn
This code is all about linear regression which is formed like a linear euqation graph using torch.nn library.

I focused on the structure of this code and try to memorize this sample code below.

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

To see same results at every time, use torch.manual_seed(num)

In [2]:
torch.manual_seed(1)

### Data

In [3]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [4]:
print(x_train)
print(x_train.shape)
print(y_train)
print(y_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])
tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


### Model Initilization

Before we used...

`W = torch.zeros(1, requires_grad= True)`

`b = torch.zeros(1, requires_grad= True)`

In this time, we will use torch.nn.Linear to make parameters.

In [5]:
model = nn.Linear(x_train.shape[1], y_train.shape[1])
#model = nn,Linear(1,1)
print(x_train.shape[1])
print(y_train.shape[1])
print(list(model.parameters()))

1
1
[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


The first element in `model.parameters()` corresponds to weight and the second element corresponds to bias, respectively.

### Optimizer


Before we used...

`optimizer = optim.SGD([W,b], lr = 0.01)`

In this time, we will use 'models.parameters' to get values of parameters.

In [6]:
optimizer = optim.SGD(model.parameters(),lr=0.01)

### Training

select epochs which is used in training step.

`hypothesis = x_train * W + b` 

`cost = torch.mean((hypothesis - y_train)**2)`

Above two codes will be replaced with below codes in `for` statement.

In [7]:
nb_epochs = 1999

In [8]:
for epoch in range(nb_epochs + 1):
    
    hypothesis = model(x_train)
    cost = F.mse_loss(hypothesis, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 ==0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/1999 Cost: 13.103541
Epoch  100/1999 Cost: 0.002791
Epoch  200/1999 Cost: 0.001724
Epoch  300/1999 Cost: 0.001066
Epoch  400/1999 Cost: 0.000658
Epoch  500/1999 Cost: 0.000407
Epoch  600/1999 Cost: 0.000251
Epoch  700/1999 Cost: 0.000155
Epoch  800/1999 Cost: 0.000096
Epoch  900/1999 Cost: 0.000059
Epoch 1000/1999 Cost: 0.000037
Epoch 1100/1999 Cost: 0.000023
Epoch 1200/1999 Cost: 0.000014
Epoch 1300/1999 Cost: 0.000009
Epoch 1400/1999 Cost: 0.000005
Epoch 1500/1999 Cost: 0.000003
Epoch 1600/1999 Cost: 0.000002
Epoch 1700/1999 Cost: 0.000001
Epoch 1800/1999 Cost: 0.000001
Epoch 1900/1999 Cost: 0.000000


## Total Code

In [9]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

model = nn.Linear(x_train.shape[1], y_train.shape[1])
#W = torch.zeros(1, requires_grad = True)
#b = torch.zeros(1, requires_grad = True)

optimizer = optim.SGD(model.parameters(), lr=1e-2)
#optimizer = optim.SGD([W,b], lr=0.01)

nb_epochs = 1999
for epoch in range(nb_epochs+1):
    hypothesis = model(x_train)
    #hypothesis = W*x_train + b
    cost = F.mse_loss(hypothesis, y_train)
    #cost = torch.mean((hypothesis - y_train)**2)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epoch % 100 ==0:
        print('Epoch: {:4d}/{}, Cost: {:.6f}'.format(epoch,nb_epochs,cost.item()))

Epoch:    0/1999, Cost: 18.562185
Epoch:  100/1999, Cost: 0.128051
Epoch:  200/1999, Cost: 0.079128
Epoch:  300/1999, Cost: 0.048896
Epoch:  400/1999, Cost: 0.030215
Epoch:  500/1999, Cost: 0.018671
Epoch:  600/1999, Cost: 0.011538
Epoch:  700/1999, Cost: 0.007129
Epoch:  800/1999, Cost: 0.004406
Epoch:  900/1999, Cost: 0.002722
Epoch: 1000/1999, Cost: 0.001682
Epoch: 1100/1999, Cost: 0.001040
Epoch: 1200/1999, Cost: 0.000642
Epoch: 1300/1999, Cost: 0.000397
Epoch: 1400/1999, Cost: 0.000245
Epoch: 1500/1999, Cost: 0.000152
Epoch: 1600/1999, Cost: 0.000094
Epoch: 1700/1999, Cost: 0.000058
Epoch: 1800/1999, Cost: 0.000036
Epoch: 1900/1999, Cost: 0.000022
