# Multivariable Linear Regression with pytorch
This code is all about Multivariable linear regression which is formed like a linear euqation graph.

I focused on the structure of this code and try to memorize this sample code below.

In [41]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

To see same results at every time, use torch.manual_seed(num)

In [42]:
torch.manual_seed(1)

### Data

In [44]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 80],
                             [96, 98, 100],
                             [73, 66, 79]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [45]:
print(x_train.size())
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


### Model Initialization

In [47]:
W = torch.zeros((3,1), requires_grad = True)
b = torch.zeros(1,requires_grad = True)

### Optimizer

In [49]:
optimizer = optim.SGD([W,b],lr = 1e-5)

### Training

In [51]:
nb_epochs = 20

In [54]:
for epoch in range(nb_epochs+1):
    hypothesis = x_train.matmul(W) + b
    
    cost = torch.mean((hypothesis - y_train)**2)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    print(hypothesis)
    print(hypothesis.squeeze())
    
    print('Epoch {:4d}/{} hypothesis: {} Cost: {:3.6f}'.format(epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()))

tensor([[153.1693],
        [184.0156],
        [174.7213],
        [197.4559],
        [146.3445]], grad_fn=<AddBackward0>)
tensor([153.1693, 184.0156, 174.7213, 197.4559, 146.3445],
       grad_fn=<SqueezeBackward0>)
Epoch    0/20 hypothesis: tensor([153.1693, 184.0156, 174.7213, 197.4559, 146.3445]) Cost: 10.239079
tensor([[153.1702],
        [184.0149],
        [174.7241],
        [197.4554],
        [146.3419]], grad_fn=<AddBackward0>)
tensor([153.1702, 184.0149, 174.7241, 197.4554, 146.3419],
       grad_fn=<SqueezeBackward0>)
Epoch    1/20 hypothesis: tensor([153.1702, 184.0149, 174.7241, 197.4554, 146.3419]) Cost: 10.229107
tensor([[153.1710],
        [184.0142],
        [174.7269],
        [197.4549],
        [146.3393]], grad_fn=<AddBackward0>)
tensor([153.1710, 184.0142, 174.7269, 197.4549, 146.3393],
       grad_fn=<SqueezeBackward0>)
Epoch    2/20 hypothesis: tensor([153.1710, 184.0142, 174.7269, 197.4549, 146.3393]) Cost: 10.219156
tensor([[153.1719],
        [184.0135],
