# Multivariable Linear Regression with pytorch using torch.nn
This code is all about Multivariable linear regression which is formed like a linear euqation graph using torch.nn library.

I focused on the structure of this code and try to memorize this sample code below.

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

To see same results at every time, use torch.manual_seed(num)

In [2]:
torch.manual_seed(1)

### Data

In [3]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 80],
                             [96, 98, 100],
                             [73, 66, 79]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [4]:
print(x_train.size())
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


### Model Initialization

Before we used...

`W = torch.zeros((3,1), requires_grad = True)`

`b = torch.zeros(1,requires_grad = True)`

In this time, we will use torch.nn.Linear to make parameters.

In [5]:
model = nn.Linear(x_train.shape[1], y_train.shape[1])
print(x_train.shape[1])
print(y_train.shape[1])

3
1


### Optimizer

previous code: `optimizer = optim.SGD([W,b],lr = 1e-5)`

In [6]:
optimizer = optim.SGD(model.parameters(),lr = 1e-5)
print(list(model.parameters()))
print(list(model.parameters())[0])
print(list(model.parameters())[0].detach())
print(type(list(model.parameters())[0].detach()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]
Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True)
tensor([[ 0.2975, -0.2548, -0.1119]])
<class 'torch.Tensor'>


### Training

In [7]:
nb_epochs = 20

In [12]:
for epoch in range(nb_epochs+1):
    #hypothesis = x_train.matmul(W) + b
    hypothesis = model(x_train)
    
    #cost = torch.mean((hypothesis - y_train)**2)
    cost = F.mse_loss(hypothesis, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    print('Epoch {:4d}/{} W:{} b:{} Cost: {:3.6f}'.format(epoch, nb_epochs, list(model.parameters())[0].detach(), list(model.parameters())[1].detach(), cost.item()))

Epoch    0/20 W:tensor([[0.9214, 0.3689, 0.5142]]) b:tensor([0.2782]) Cost: 1006.170715
Epoch    1/20 W:tensor([[0.9517, 0.3993, 0.5443]]) b:tensor([0.2786]) Cost: 325.436646
Epoch    2/20 W:tensor([[0.9688, 0.4165, 0.5611]]) b:tensor([0.2788]) Cost: 110.561928
Epoch    3/20 W:tensor([[0.9783, 0.4263, 0.5704]]) b:tensor([0.2789]) Cost: 42.729458
Epoch    4/20 W:tensor([[0.9837, 0.4319, 0.5755]]) b:tensor([0.2790]) Cost: 21.309166
Epoch    5/20 W:tensor([[0.9868, 0.4352, 0.5783]]) b:tensor([0.2790]) Cost: 14.538325
Epoch    6/20 W:tensor([[0.9885, 0.4371, 0.5797]]) b:tensor([0.2790]) Cost: 12.391404
Epoch    7/20 W:tensor([[0.9895, 0.4383, 0.5804]]) b:tensor([0.2790]) Cost: 11.703969
Epoch    8/20 W:tensor([[0.9901, 0.4391, 0.5806]]) b:tensor([0.2790]) Cost: 11.477208
Epoch    9/20 W:tensor([[0.9904, 0.4396, 0.5806]]) b:tensor([0.2790]) Cost: 11.395860
Epoch   10/20 W:tensor([[0.9906, 0.4401, 0.5805]]) b:tensor([0.2790]) Cost: 11.360420
Epoch   11/20 W:tensor([[0.9908, 0.4404, 0.5803]])