# Softmax Regression with pytorch
This code is all about softmax regression which can classify more than two kinds of groups.

I focused on the structure of this code and try to memorize this sample code below.

## Prerequisite for making softmax Regression model

### Make one-hot-encoded data

In [6]:
import torch
import torch.nn.functional as F

In [7]:
torch.manual_seed(1)

In [8]:
z = torch.FloatTensor([1,2,3])

In [9]:
hypothesis = F.softmax(z, dim=0)
print(hypothesis)
print(type(hypothesis))

tensor([0.0900, 0.2447, 0.6652])
<class 'torch.Tensor'>


In [10]:
hypothesis = F.softmax(z)
print(hypothesis)

tensor([0.0900, 0.2447, 0.6652])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.


In [11]:
hypothesis.sum()

tensor(1.)

In [12]:
z = torch.rand(3,5, requires_grad=True)
print(z)

tensor([[0.7576, 0.2793, 0.4031, 0.7347, 0.0293],
        [0.7999, 0.3971, 0.7544, 0.5695, 0.4388],
        [0.6387, 0.5247, 0.6826, 0.3051, 0.4635]], requires_grad=True)


In [13]:
hypothesis = F.softmax(z, dim=0)
print(hypothesis)
hypothesis_sum = hypothesis.sum(dim=0)
print(hypothesis_sum)
print(hypothesis_sum.shape)

tensor([[0.3412, 0.2938, 0.2671, 0.4002, 0.2469],
        [0.3559, 0.3306, 0.3796, 0.3393, 0.3719],
        [0.3029, 0.3756, 0.3533, 0.2605, 0.3812]], grad_fn=<SoftmaxBackward>)
tensor([1., 1., 1., 1., 1.], grad_fn=<SumBackward1>)
torch.Size([5])


In [14]:
hypothesis = F.softmax(z, dim=1)
print(hypothesis)
hypothesis_sum = hypothesis.sum(dim=1)
print(hypothesis_sum)
print(hypothesis_sum.shape)

tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward>)
tensor([1.0000, 1.0000, 1.0000], grad_fn=<SumBackward1>)
torch.Size([3])


In [15]:
y = torch.randint(5, (3,)).long()
print(y)

tensor([0, 2, 1])


In [16]:
y_one_hot = torch.zeros_like(hypothesis)

In [17]:
print(y_one_hot)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [18]:
y_one_hot.scatter_(1,y.unsqueeze(1),1)

tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]])

### Make softmax regression cost function

`(y_one_hot * -torch.log(F.softmax(z, dim=1))).sum(dim=1).mean()`
upper code can be converted to `F.cross_entropy(z,y)`

z is three values which comes from results of matrix product. and y_one_hot is a l

## Softmax Regression model

In [19]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [20]:
torch.manual_seed(1)

###Data

In [32]:
x_train = [[1, 2, 1, 1],
           [2, 1, 3, 2],
           [3, 1, 3, 4],
           [4, 1, 5, 5],
           [1, 7, 5, 5],
           [1, 2, 5, 6],
           [1, 6, 6, 6],
           [1, 7, 7, 7]]
y_train = [2, 2, 2, 1, 1, 1, 0, 0]
x_train = torch.FloatTensor(x_train)
y_train = torch.LongTensor(y_train)

In [33]:
y_one_hot = torch.zeros(x_train.shape[0],3)
y_one_hot.scatter_(1,y_train.unsqueeze(1),1)
print(y_one_hot)

tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])


###Model

In [34]:
W = torch.zeros(4,3, requires_grad=True)
b = torch.zeros(1, requires_grad = True)

###Optimizer

In [35]:
optimizer = optim.SGD([W,b], lr = 0.1)

###Training

In [36]:
nb_epochs = 1000
for epoch in range(nb_epochs+1):
    hypothesis = F.softmax(x_train.matmul(W)+b, dim=1)
    cost = (y_one_hot * (-torch.log(hypothesis))).sum(dim=1).mean()

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch: {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs,cost.item()))

Epoch:    0/1000 Cost: 1.098612
Epoch:  100/1000 Cost: 0.761050
Epoch:  200/1000 Cost: 0.689991
Epoch:  300/1000 Cost: 0.643229
Epoch:  400/1000 Cost: 0.604117
Epoch:  500/1000 Cost: 0.568255
Epoch:  600/1000 Cost: 0.533922
Epoch:  700/1000 Cost: 0.500291
Epoch:  800/1000 Cost: 0.466908
Epoch:  900/1000 Cost: 0.433507
Epoch: 1000/1000 Cost: 0.399962
